### PR TITLE
Track corejavacript version

### PR DESCRIPTION
**Pull request by loop23**
The original upstream source for the javascript library is unmantained, 
Sorry I wasn't quite sure what to put in version, upstream still reports 0.11.1 even if it changed from what it was.

Bye

### CODE REVIEW

**Comment by freemanoid** [comment]
@yourabi hey, is there any issues with this PR? What prevents it from merge?

**Comment by yourabi** [comment]
@freemanoid no, I'll take a look and package a release

**Comment by bkeese** [comment]
@yourabi @freemanoid, We are particularly keen to get this bugfix merged: https://github.com/loop23/twitter-typeahead-rails/commit/f200f9b8d2e5232e3e740bde2f4232f4e6224738#diff-08ec0c9be65fd785bf30d14e2f81de6eL810. Thank you so much.

**Comment by freemanoid** [comment]
hey @yourabi thanks for merging this. Could you please make a release with this fix?

**Comment by teohm** [comment]
@yourabi @freemanoid what version number should we use for the release?

**Comment by freemanoid** [comment]
ping @yourabi

**Pull request merged**
